import "./globals.css";
import Nav from "@/components/navigation/nav"
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import Toaster from "@/components/ui/toaster";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className={cn("w-full mx-auto")}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          
          <Nav />
          <Toaster />
          {children}
          </ThemeProvider>
        </body>
    </html>
  );
}
